### ISSUE TITLE
Test::Exception not listed as prerequisite

### ISSUE THREAD

**Issue by perlpunk** [wreis/DBIx-Class-EncodedColumn#10]
`t/crypt.t` is using Test::Exception, but it's not listed in `Makefile.PL` or `META.yml`
```
t/crypt.t ................. Can't locate Test/Exception.pm in @INC
```

**Comment by wreis** [comment]
Good catch! Could you please send a PR?

**Comment by perlpunk** [comment]
done :)

Also `.` is still missing in `@INC` (https://rt.cpan.org/Public/Bug/Display.html?id=121903)

Do you want a PR for that too?

**Comment by wreis** [comment]
Yeah, that is a feature in recent perl. If you could send a PR, I'd love to merge it!

**Comment by perlpunk** [comment]
btw, I found this issue because we at SUSE are building all CPAN packages in Open Build System (OBS):
https://build.opensuse.org/package/show/devel:languages:perl:CPAN-D/perl-DBIx-Class-EncodedColumn
Because the packages are built without the test depencendies from other modules, this kind of issue pops up more often than for regular testers.
A link to OBS will probably be added soon to the testers matrix, so people can check build results there too.

**Comment by perlpunk** [comment]
Created #12

**Comment by wreis** [comment]
> btw, I found this issue because we at SUSE are building all CPAN packages in Open Build System (OBS):

Very nice! Handy in order to improve CPAN packages. Thanks!

**Comment by perlpunk** [comment]
Hm, in the newest version it's in the `Makefile.PL`, but still not in `META.yml`.

I don't yet fully know our tool which reads the dependencies automatically, but it's not listing `Test::Exception`.

Another thing which could be improved: `DBIx-Class-EncodedColumn-0.00017.tar.gz` extracts to `DBIx-Class-EncodedColumn/` instead of `DBIx-Class-EncodedColumn-0.00017/`.

I just fixed our tool to be able to deal with that, but it's in general a good idea that such a tarball extracts to a path with a version number.

Also there is a problem with Module::Install now: http://matrix.cpantesters.org/?dist=DBIx-Class-EncodedColumn+0.00017
