### ISSUE TITLE
components loading order can affect the result

### ISSUE THREAD

**Issue by aanoaa** [wreis/DBIx-Class-EncodedColumn#2]
hi.
I usually using `result_base_class` for prevent loading components multiple times.

```perl
package App::Schema::Parent;
use Moose;
use MooseX::NonMoose;
use namespace::autoclean;

extends 'DBIx::Class::Core';

__PACKAGE__->load_components(qw/
    InflateColumn::DateTime
    TimeStamp
    EncodedColumn
/);

__PACKAGE__->meta->make_immutable;

1;
```

above, `EncodedColumn` is display after `TimeStamp`.

if derived class extends this class, EncodedColumn is not working.
here is my test file. https://dl.dropboxusercontent.com/u/16719710/tmp/oops.tar.gz
execute for just type `perl test.pl`

if switching `EncodedColumn` and `TimeStamp` position,
it works.

I don't know this issue associate with this modules.
maybe this is more associate with `DBIx::Class` core.

thanks.

**Comment by wreis** [comment]
Fixed in 1f0c37d64c.
